version: 2
updates:
  # Update Go dependencies
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"

  # Update GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Update Go version in go.mod
  - package-ecosystem: "gomod"
    directory: "/"
    target-branch: "main"
    rebase-strategy: "auto"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    allow:
      - dependency-type: "all"
    labels:
      - "dependencies"
      - "go version update"
